import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1758401111314 implements MigrationInterface {
    name = 'InitSchema1758401111314'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "work_schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "userId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "startTime" TIME, "endTime" TIME, "isDayOff" boolean NOT NULL DEFAULT false, "breakStartTime" TIME, "breakEndTime" TIME, "efficiency" numeric(3,2) NOT NULL DEFAULT '1', "skillMatrix" jsonb DEFAULT ('[]')::jsonb, "shiftType" character varying(50) NOT NULL DEFAULT 'flexible', "maxConsecutiveDays" integer NOT NULL DEFAULT '5', "preferredDaysOff" jsonb DEFAULT ('[]')::jsonb, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_work_schedule_company_user_day" UNIQUE ("companyId", "userId", "dayOfWeek"), CONSTRAINT "chk_ws_shift_duration_bounds" CHECK (("isDayOff" = true) OR ((EXTRACT(EPOCH FROM ("endTime"::time - "startTime"::time))/3600) BETWEEN 2 AND 12)), CONSTRAINT "chk_ws_break_duration_bounds" CHECK ((("breakStartTime" IS NULL AND "breakEndTime" IS NULL) OR ((EXTRACT(EPOCH FROM ("breakEndTime"::time - "breakStartTime"::time))/60) BETWEEN 15 AND 120))), CONSTRAINT "chk_ws_break_within_work" CHECK (("breakStartTime" IS NULL AND "breakEndTime" IS NULL) OR ("breakStartTime" >= "startTime" AND "breakEndTime" <= "endTime" AND "breakEndTime" > "breakStartTime")), CONSTRAINT "chk_ws_efficiency_bounds" CHECK (("efficiency" >= 0.5 AND "efficiency" <= 2.0)), CONSTRAINT "chk_ws_time_range" CHECK (("isDayOff" = true) OR ("endTime" > "startTime")), CONSTRAINT "PK_f5251879700e5ca0d2e353fa34f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_work_schedule_company_day" ON "work_schedules" ("companyId", "dayOfWeek") `);
        await queryRunner.query(`CREATE INDEX "idx_work_schedule_company_active" ON "work_schedules" ("companyId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "idx_work_schedule_company" ON "work_schedules" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "legal_name" character varying(255) NOT NULL, "tax_number" character varying(12), "address" text, "phone" character varying(20), "email" character varying(255) NOT NULL, "website" character varying(500), "logo_url" character varying(1000), "working_hours" jsonb, "is_active" boolean NOT NULL DEFAULT true, "data_retention_until" TIMESTAMP WITH TIME ZONE, "pdp_consent_version" character varying(50), "pdp_consent_date" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d0af6f5866201d5cb424767744a" UNIQUE ("email"), CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id")); COMMENT ON COLUMN "companies"."name" IS 'Название компании (ПДн при наличии ИП)'; COMMENT ON COLUMN "companies"."legal_name" IS 'Юридическое название'; COMMENT ON COLUMN "companies"."tax_number" IS 'ИНН (ПДн для ИП)'; COMMENT ON COLUMN "companies"."address" IS 'Адрес (может содержать ПДн)'; COMMENT ON COLUMN "companies"."phone" IS 'Телефон компании'; COMMENT ON COLUMN "companies"."email" IS 'Email компании'; COMMENT ON COLUMN "companies"."working_hours" IS 'Часы работы в формате JSON'; COMMENT ON COLUMN "companies"."data_retention_until" IS 'Дата до которой храним ПДн компании (152-ФЗ)'; COMMENT ON COLUMN "companies"."pdp_consent_version" IS 'Версия согласия на обработку ПДн'; COMMENT ON COLUMN "companies"."pdp_consent_date" IS 'Дата согласия на обработку ПДн'`);
        await queryRunner.query(`CREATE INDEX "IDX_774de87b5d9acde9112a1645ef" ON "companies" ("tax_number") WHERE tax_number IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_b559ae26b6f801536d28109453" ON "companies" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d0632c00306eec5feecbbdc9f" ON "companies" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8f4e9c088ad9e60af1a7d1193d" ON "companies" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "type" character varying(20) NOT NULL DEFAULT 'individual', "first_name" character varying(100), "last_name" character varying(100), "company_name" character varying(255), "tax_number" character varying(50), "email" character varying(255) NOT NULL, "email_normalized" character varying(255) NOT NULL, "phone" character varying(50) NOT NULL, "phone_e164" character varying(20), "address" text, "source" character varying(50), "loyalty_points" integer NOT NULL DEFAULT '0', "notes" text, "is_active" boolean NOT NULL DEFAULT true, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "marketing_consent" boolean NOT NULL DEFAULT false, "marketing_consent_date" TIMESTAMP WITH TIME ZONE, "pdp_consent_version" character varying(50), "pdp_consent_date" TIMESTAMP WITH TIME ZONE, "data_retention_until" TIMESTAMP WITH TIME ZONE, "anonymized_at" TIMESTAMP WITH TIME ZONE, "anonymized_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a21e0c622ad0d6376e813e4317" ON "customers" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_49fcf0b823276d66af6f0c3868" ON "customers" ("company_id", "phone_e164") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_580988896ad56541ddab92aace" ON "customers" ("company_id", "email_normalized") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_946a7a5519eab49537ba6be271" ON "customers" ("email", "company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0e29920aaf871f3eddbea69f0" ON "customers" ("company_id") `);
        await queryRunner.query(`CREATE TABLE "vehicle_brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "name_normalized" character varying(110) NOT NULL, "country" character varying(50), "logo_url" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "is_verified" boolean NOT NULL DEFAULT false, "aliases" text, "source" character varying(30), "source_id" character varying(100), "reviewed_at" TIMESTAMP WITH TIME ZONE, "reviewed_by_user_id" uuid, "assignee_user_id" uuid, "moderation_notes" text, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3ede5be03b371734e1d8aa257c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f5a532698b4aabfd1526c4745" ON "vehicle_brands" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_a934f45da52f7519d515cd1df0" ON "vehicle_brands" ("is_verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7a9a7fe16791a075d6c4f9bf5" ON "vehicle_brands" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_47141a92885dcbcab5cc815f1c" ON "vehicle_brands" ("is_deleted") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_11f4754bf8fc4c02fd6d964724" ON "vehicle_brands" ("name_normalized") WHERE is_deleted = false`);
        await queryRunner.query(`CREATE TABLE "vehicle_models" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "brand_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "name_normalized" character varying(110) NOT NULL, "year_from" integer, "year_to" integer, "class" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "is_verified" boolean NOT NULL DEFAULT false, "aliases" text, "source" character varying(30), "source_id" character varying(100), "reviewed_at" TIMESTAMP WITH TIME ZONE, "reviewed_by_user_id" uuid, "assignee_user_id" uuid, "moderation_notes" text, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1c01752184334fdbcae9bbaa67f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_92932f12363389355657c9f54a" ON "vehicle_models" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_d03b990e547e1715fd8083399a" ON "vehicle_models" ("is_verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_eea946a495b5724fd8b31149aa" ON "vehicle_models" ("is_deleted") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bddf5fcb0c09ab5d6ccd46e8d9" ON "vehicle_models" ("brand_id", "name_normalized") WHERE is_deleted = false`);
        await queryRunner.query(`CREATE INDEX "IDX_e71c84a17f9c006260e2d487c0" ON "vehicle_models" ("brand_id") `);
        await queryRunner.query(`CREATE TABLE "vehicle_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "name_normalized" character varying(110) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "is_verified" boolean NOT NULL DEFAULT false, "reviewed_at" TIMESTAMP WITH TIME ZONE, "reviewed_by_user_id" uuid, "assignee_user_id" uuid, "moderation_notes" text, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_73d1e40f4add7f4f6947acad3a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0474220020aff2d7f6d3b80a27" ON "vehicle_types" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_8caa82b996288ac4e7a3090ff4" ON "vehicle_types" ("is_verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_74a36c6f923c86278b726e9881" ON "vehicle_types" ("is_deleted") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_007a712afe075e18d9d822f6fb" ON "vehicle_types" ("name_normalized") WHERE is_deleted = false`);
        await queryRunner.query(`CREATE TABLE "vehicles_service_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "company_id" uuid NOT NULL, "order_id" uuid, "date" date NOT NULL, "mileage" integer, "description" text NOT NULL, "next_service_date" date, "notes" text, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_06dae9ee9f5e7e93139bf64ccbf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e96c683d729bb813d19ae173cb" ON "vehicles_service_history" ("next_service_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3866b386f2136abf529d03d122" ON "vehicles_service_history" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a99214791d317ed73db1c4969" ON "vehicles_service_history" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c5a6ccfab11cdba2bf2d4b3bc" ON "vehicles_service_history" ("vehicle_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9af62cc972a0a9b7eb56d89b07" ON "vehicles_service_history" ("company_id") `);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "company_id" uuid NOT NULL, "model_id" uuid NOT NULL, "vehicle_type_id" uuid NOT NULL, "vin" character varying(17), "license_plate" character varying(20), "year" integer, "color" character varying(50), "engine_type" character varying(20) DEFAULT 'petrol', "engine_volume" numeric(3,1), "mileage" integer, "last_service_date" date, "next_service_date" date, "notes" text, "is_active" boolean NOT NULL DEFAULT true, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_8a47f365d62f22d40a3d0eefa5" CHECK ("year" IS NULL OR "year" <= EXTRACT(YEAR FROM CURRENT_DATE) + 2), CONSTRAINT "CHK_df8acc044aac88d2e3da07e84f" CHECK ("year" IS NULL OR "year" >= 1900), CONSTRAINT "CHK_20fd5c59bc2c7ed6712f9d793d" CHECK ("engine_volume" IS NULL OR ("engine_volume" >= 0.1 AND "engine_volume" <= 20.0)), CONSTRAINT "CHK_d978e66780432b3f16adc57b89" CHECK ("mileage" IS NULL OR "mileage" >= 0), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_216b6063df0b6aedf55180f91f" ON "vehicles" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_805f65c04948d4e5006b3b2de2" ON "vehicles" ("is_deleted") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_534329c0c56af9bd284a18acc6" ON "vehicles" ("license_plate", "company_id") WHERE license_plate IS NOT NULL AND is_deleted = false`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_33467e9fe9f0278ffc281ccba9" ON "vehicles" ("vin") WHERE vin IS NOT NULL AND is_deleted = false`);
        await queryRunner.query(`CREATE INDEX "IDX_c1cda98f67cb9c79a1f1153e62" ON "vehicles" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e11ef2dcd880132d31bd9f92c2" ON "vehicles" ("company_id") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "code" character varying(100) NOT NULL, "description" text, "group" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "description" text, "is_system" boolean NOT NULL DEFAULT false, "company_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9acb61b0b5c438c8c68f6eb91a1" UNIQUE ("name", "company_id"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "phone" character varying(50), "avatar_url" character varying(255), "specialization" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP, "role_id" uuid NOT NULL, "two_factor_enabled" boolean NOT NULL DEFAULT false, "two_factor_secret" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "device_id" character varying(100) NOT NULL, "device_name" character varying(255), "refresh_token_hash" character varying(255) NOT NULL, "jti" character varying(64) NOT NULL, "user_agent" text NOT NULL, "ip_address" character varying(45) NOT NULL, "ip_subnet" character varying(64), "expires_at" TIMESTAMP NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "last_used_at" TIMESTAMP, "device_fingerprint" character varying(64), "compromised_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_consents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "consent_type" character varying(50) NOT NULL, "policy_version" character varying(20) NOT NULL, "policy_text_hash" character varying(64) NOT NULL, "ip_address" character varying(45), "user_agent" text, "granted_at" TIMESTAMP NOT NULL DEFAULT now(), "revoked_at" TIMESTAMP, CONSTRAINT "PK_65e4c6d6204ad8719abf4b30326" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6283f1222bdc2390cf16836ce7" ON "user_consents" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc51c44e296132242ed415f181" ON "user_consents" ("consent_type") `);
        await queryRunner.query(`CREATE TABLE "tariffs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "name_normalized" character varying(100) NOT NULL, "description" text, "price_monthly" numeric(10,2) NOT NULL, "price_yearly" numeric(10,2) NOT NULL, "max_users" integer, "max_customers" integer, "max_vehicles" integer, "max_orders" integer, "features" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_tariffs_name_normalized" UNIQUE ("name_normalized"), CONSTRAINT "CHK_7039e890ed61e0a0268a7af775" CHECK ("max_orders" IS NULL OR "max_orders" >= -1), CONSTRAINT "CHK_6f1a9b629b540ebcc313ff6421" CHECK ("max_vehicles" IS NULL OR "max_vehicles" >= -1), CONSTRAINT "CHK_f9c0e14acdacdb56ae88d309e2" CHECK ("max_customers" IS NULL OR "max_customers" >= -1), CONSTRAINT "CHK_5da14a9b52f7dd21724b2985c3" CHECK ("max_users" IS NULL OR "max_users" >= -1), CONSTRAINT "CHK_dc6bd452fec211f4ef1686206e" CHECK ("price_monthly" >= 0 AND "price_yearly" >= 0), CONSTRAINT "PK_7f32baf8d8b4bb0cf4d7ac97741" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_tariffs_name" ON "tariffs" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_tariffs_active" ON "tariffs" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_tariffs_created_at" ON "tariffs" ("created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_suppliertype_enum" AS ENUM('manufacturer', 'distributor', 'wholesaler', 'retailer', 'service_provider', 'other')`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "name" character varying(255) NOT NULL, "contactName" character varying(100), "email" character varying(255), "phone" character varying(50), "address" text, "city" character varying(100), "country" character varying(100), "taxNumber" character varying(50), "website" character varying(255), "supplierType" "public"."suppliers_suppliertype_enum" NOT NULL DEFAULT 'distributor', "paymentTerms" character varying(200), "deliveryTerms" character varying(200), "notes" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_suppliers_company_taxnumber_unique" ON "suppliers" ("companyId", "taxNumber") WHERE "taxNumber" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_suppliers_company_email_unique" ON "suppliers" ("companyId", "email") WHERE "email" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_suppliers_isactive" ON "suppliers" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "idx_suppliers_companyid" ON "suppliers" ("companyId") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_status_enum" AS ENUM('active', 'pending', 'suspended', 'canceled', 'expired', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "tariff_id" uuid NOT NULL, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."subscription_status_enum" NOT NULL DEFAULT 'pending', "payment_method" character varying(50), "auto_renew" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_dda3fb4d7663484b2e08a521eb" CHECK ("end_date" > "start_date"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e3cc01c420db5151aa2136035" ON "subscriptions" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_349405bc66ac45d86a24f562e7" ON "subscriptions" ("end_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_active_subscription_per_company" ON "subscriptions" ("company_id") WHERE status = 'active'`);
        await queryRunner.query(`CREATE INDEX "idx_subscriptions_company_end_date" ON "subscriptions" ("company_id", "end_date") `);
        await queryRunner.query(`CREATE INDEX "idx_subscriptions_company_status" ON "subscriptions" ("company_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_payment_status_enum" AS ENUM('pending', 'completed', 'failed', 'refunded', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_payment_method_type_enum" AS ENUM('card', 'mir', 'sbp', 'wallet', 'bank_transfer')`);
        await queryRunner.query(`CREATE TABLE "subscription_payment_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscription_id" uuid, "company_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'RUB', "status" "public"."subscription_payment_status_enum" NOT NULL DEFAULT 'pending', "gateway_type" character varying(50), "gateway_transaction_id" character varying(255), "gateway_response" jsonb, "mir_card_used" boolean NOT NULL DEFAULT false, "payment_method_type" "public"."subscription_payment_method_type_enum", "payment_system_compliance" jsonb, "aml_check_status" character varying(20) NOT NULL DEFAULT 'pending', "aml_risk_score" integer NOT NULL DEFAULT '0', "suspicious_activity_reported" boolean NOT NULL DEFAULT false, "user_ip_address" character varying(255), "user_agent" text, "processing_location" character varying(10) NOT NULL DEFAULT 'RU', "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2bcf98e2ced7140669c961db1c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_73b063088c84f0070d5c622108" ON "subscription_payment_logs" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c973220739e2a277deaa8e2ecc" ON "subscription_payment_logs" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c40c4d9508a8edfad0104b8e2" ON "subscription_payment_logs" ("amount") `);
        await queryRunner.query(`CREATE INDEX "IDX_569039d8fb7f0d507e8296d9b8" ON "subscription_payment_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_05ed0c14282337b6b6da805c01" ON "subscription_payment_logs" ("mir_card_used") `);
        await queryRunner.query(`CREATE INDEX "IDX_46b3c58aadafa36dc09dc56dac" ON "subscription_payment_logs" ("aml_risk_score") `);
        await queryRunner.query(`CREATE INDEX "IDX_e44cc8ba7fa6c080a4810bba08" ON "subscription_payment_logs" ("suspicious_activity_reported") `);
        await queryRunner.query(`CREATE INDEX "IDX_29b75ed40678523f6f34c8e584" ON "subscription_payment_logs" ("created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_gateway_tx" ON "subscription_payment_logs" ("gateway_type", "gateway_transaction_id") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_consent_type_enum" AS ENUM('pdn_processing', 'pdn_storage', 'marketing', 'analytics', 'third_party_sharing')`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_consent_status_enum" AS ENUM('granted', 'revoked', 'expired', 'pending')`);
        await queryRunner.query(`CREATE TABLE "subscription_consents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscription_id" uuid NOT NULL, "company_id" uuid NOT NULL, "user_id" uuid, "consent_type" "public"."subscription_consent_type_enum" NOT NULL, "status" "public"."subscription_consent_status_enum" NOT NULL DEFAULT 'pending', "consent_text" text, "consent_text_hash" character varying(64), "policy_version" character varying(20), "data_categories" jsonb NOT NULL, "processing_purposes" jsonb NOT NULL, "retention_period_days" integer NOT NULL, "granted_at" TIMESTAMP WITH TIME ZONE, "revoked_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "ip_address" character varying(255) NOT NULL, "user_agent" text, "consent_method" character varying(50) NOT NULL, "legal_basis" character varying(100) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_89c08ae316f1a929e9a62f0d718" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aca8064488e9cb39b7ecd8ea89" ON "subscription_consents" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b727419f868a56f5567797101" ON "subscription_consents" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0b580252fad2055064fdca4a9" ON "subscription_consents" ("consent_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_e308eb9e8f2abc30eaa067959b" ON "subscription_consents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_860ee1954cafb7cde803ee9444" ON "subscription_consents" ("created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_active_consent_per_type" ON "subscription_consents" ("subscription_id", "consent_type") WHERE status = 'granted'`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_compliance_type_enum" AS ENUM('fz242', 'fz152', 'fz161', 'fz115', 'consumer_rights', 'data_protection')`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_compliance_action_enum" AS ENUM('granted', 'revoked', 'checked', 'violated', 'remediated', 'reported')`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_compliance_status_enum" AS ENUM('compliant', 'violation', 'warning', 'pending')`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_compliance_risk_level_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "subscription_compliance_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "subscription_id" uuid, "compliance_type" "public"."subscription_compliance_type_enum" NOT NULL, "law_reference" character varying(100), "action" "public"."subscription_compliance_action_enum" NOT NULL, "status" "public"."subscription_compliance_status_enum" NOT NULL DEFAULT 'compliant', "description" text, "violation_details" jsonb, "remediation_actions" jsonb, "user_id" uuid, "user_ip_address" character varying(255), "user_agent" text, "server_location" character varying(10) NOT NULL DEFAULT 'RU', "data_processing_location" character varying(10) NOT NULL DEFAULT 'RU', "compliance_version" character varying(10) NOT NULL DEFAULT '1.0', "metadata" jsonb, "risk_level" "public"."subscription_compliance_risk_level_enum" NOT NULL DEFAULT 'low', "requires_notification" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "resolved_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1737df8cce27edb60872251912d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_073984be2b176a70a12bba6db9" ON "subscription_compliance_logs" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7842d33badf0159a415e5bd29b" ON "subscription_compliance_logs" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_67b1f10f57ded0fb49d46477e1" ON "subscription_compliance_logs" ("compliance_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c74a5323cfdb34d2acc50aff6" ON "subscription_compliance_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a3c76ee765376431d8f927858" ON "subscription_compliance_logs" ("risk_level") `);
        await queryRunner.query(`CREATE INDEX "IDX_81fbd794573a01d5e004f85c84" ON "subscription_compliance_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_comp_logs_company_created" ON "subscription_compliance_logs" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "part_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid, "name" character varying(100) NOT NULL, "description" text, "code" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6070cc11099e9ef60593846832c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "parts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "categoryId" uuid NOT NULL, "name" character varying(255) NOT NULL, "partNumber" character varying(100), "brand" character varying(100), "description" text, "costPrice" numeric(10,2) NOT NULL DEFAULT '0', "sellingPrice" numeric(10,2) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "imageUrl" character varying(500), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "category_id" uuid, CONSTRAINT "chk_parts_sellingprice_nonneg" CHECK ("sellingPrice" >= 0), CONSTRAINT "chk_parts_costprice_nonneg" CHECK ("costPrice" >= 0), CONSTRAINT "PK_daa5595bb8933f49ac00c9ebc79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_parts_company_partnumber_unique" ON "parts" ("companyId", "partNumber") WHERE "partNumber" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_parts_createdat" ON "parts" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_parts_categoryid" ON "parts" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "idx_parts_companyid" ON "parts" ("companyId") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_type_enum" AS ENUM('receipt', 'issue', 'adjustment', 'transfer', 'reservation', 'release')`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_reason_enum" AS ENUM('purchase', 'order_fulfillment', 'inventory_count', 'damage', 'expiry', 'loss', 'correction')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "partId" uuid NOT NULL, "orderId" uuid, "supplierId" uuid, "type" "public"."stock_movements_type_enum" NOT NULL, "reason" "public"."stock_movements_reason_enum" NOT NULL, "quantity" integer NOT NULL, "price" numeric(10,2), "totalAmount" numeric(10,2), "documentNumber" character varying(100), "notes" text, "createdBy" uuid NOT NULL, "reversedByMovementId" uuid, "reversesMovementId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "part_id" uuid, "supplier_id" uuid, CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "categoryId" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "price" numeric(10,2) NOT NULL, "durationMinutes" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_exceptions_type_enum" AS ENUM('vacation', 'sick_leave', 'holiday', 'training', 'overtime', 'personal')`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_exceptions_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "schedule_exceptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "userId" uuid NOT NULL, "type" "public"."schedule_exceptions_type_enum" NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isFullDay" boolean NOT NULL DEFAULT true, "startTime" TIME, "endTime" TIME, "reason" text, "status" "public"."schedule_exceptions_status_enum" NOT NULL DEFAULT 'pending', "approvedBy" uuid, "approvedAt" TIMESTAMP WITH TIME ZONE, "rejectionReason" text, "affectedAppointments" jsonb NOT NULL DEFAULT ('[]')::jsonb, "coverageAnalysis" jsonb, "dataRetentionUntil" TIMESTAMP WITH TIME ZONE, "anonymizedAt" TIMESTAMP WITH TIME ZONE, "anonymizedBy" uuid, "piiAnonymized" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "chk_se_partial_time_valid" CHECK (("isFullDay" = true) OR ("startTime" IS NOT NULL AND "endTime" IS NOT NULL AND "endTime" > "startTime")), CONSTRAINT "chk_se_date_range" CHECK (("endDate" >= "startDate")), CONSTRAINT "PK_829b77f6edcc7e36993664df455" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_se_company_retention" ON "schedule_exceptions" ("companyId", "dataRetentionUntil") `);
        await queryRunner.query(`CREATE INDEX "idx_se_company_start_end" ON "schedule_exceptions" ("companyId", "startDate", "endDate") `);
        await queryRunner.query(`CREATE INDEX "idx_se_company_status" ON "schedule_exceptions" ("companyId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_se_company_user" ON "schedule_exceptions" ("companyId", "userId") `);
        await queryRunner.query(`CREATE TABLE "service_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid, "name" character varying(100) NOT NULL, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fe4da5476c4ffe5aa2d3524ae68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "serviceId" uuid NOT NULL, "price" numeric(10,2) NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "discountPercent" numeric(5,2) NOT NULL DEFAULT '0', "totalAmount" numeric(10,2) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'planned', "mechanicId" uuid, "startTime" TIMESTAMP WITH TIME ZONE, "endTime" TIMESTAMP WITH TIME ZONE, "notes" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_74f048f792fe40516ac248ce060" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e886c578320ba8364b93266ec" ON "order_services" ("mechanicId") `);
        await queryRunner.query(`CREATE INDEX "IDX_714fa9ff7e2a619c3102352fd1" ON "order_services" ("serviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_db8265e367f7c973cd4fe5e17a" ON "order_services" ("orderId") `);
        await queryRunner.query(`CREATE TABLE "order_parts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "partId" uuid NOT NULL, "price" numeric(10,2) NOT NULL, "quantity" integer NOT NULL, "discountPercent" numeric(5,2) NOT NULL DEFAULT '0', "totalAmount" numeric(10,2) NOT NULL, "isCustomerProvided" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5ddaf71b0958a588005f70373a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_009833ff74f9f66e1ab72a9732" ON "order_parts" ("partId") `);
        await queryRunner.query(`CREATE INDEX "IDX_790f388a94f5ffc752754e3d0f" ON "order_parts" ("orderId") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "customerId" uuid NOT NULL, "vehicleId" uuid NOT NULL, "orderNumber" character varying(50) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'new', "createdBy" uuid NOT NULL, "assignedTo" uuid, "description" text, "customerComplaints" text, "diagnosticResults" text, "totalAmount" numeric(15,2) NOT NULL DEFAULT '0', "discountAmount" numeric(15,2) NOT NULL DEFAULT '0', "taxAmount" numeric(15,2) NOT NULL DEFAULT '0', "finalAmount" numeric(15,2) NOT NULL DEFAULT '0', "mileage" integer, "estimatedCompletionTime" TIMESTAMP WITH TIME ZONE, "actualCompletionTime" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id")); COMMENT ON COLUMN "orders"."status" IS 'Статус заказа (enum как строка)'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_60cc1394b230eb43e4e415eda3" ON "orders" ("companyId", "orderNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d3f1e17e30b7540ca84036307" ON "orders" ("assignedTo") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d17fd47a7bbf512e58209fbb3" ON "orders" ("createdBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_19b96cf049d221b5731e4ed9b7" ON "orders" ("vehicleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5de51ca888d8b1f5ac25799dd" ON "orders" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b6fe899d5ca4a3f5925463990d" ON "orders" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "orderId" uuid NOT NULL, "invoiceNumber" character varying(50) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'issued', "issueDate" date NOT NULL, "dueDate" date NOT NULL, "amount" numeric(15,2) NOT NULL, "taxAmount" numeric(15,2) NOT NULL, "totalAmount" numeric(15,2) NOT NULL, "notes" text, "fiscalizationStatus" character varying(20) NOT NULL DEFAULT 'not_required', "fiscalizedAt" TIMESTAMP WITH TIME ZONE, "ofdProvider" character varying(100), "ofdReceiptUrl" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5306b1cb7e79346085c73c0480" ON "invoices" ("companyId", "invoiceNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_affa881df04ba2db0fce590be4" ON "invoices" ("fiscalizationStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_41ee6a6636d48aac700fb52e0b" ON "invoices" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a58a78a0e0031dd93a2f56f1e8" ON "invoices" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b793047e7030ef060eaae8438" ON "invoices" ("companyId") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_type_enum" AS ENUM('cash', 'card', 'bank_transfer', 'installments', 'corporate', 'digital_wallet', 'cryptocurrency')`);
        await queryRunner.query(`CREATE TABLE "payment_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "type" "public"."payment_method_type_enum" NOT NULL DEFAULT 'cash', "processing_fee_percent" numeric(5,2), "min_amount" numeric(12,2), "max_amount" numeric(12,2), "daily_transaction_limit" integer, "supports_refunds" boolean NOT NULL DEFAULT true, "requires_verification" boolean NOT NULL DEFAULT false, "installment_max_period_months" integer, "installment_interest_rate" numeric(5,2), "installment_min_down_payment_percent" numeric(5,2), "gateway_type" character varying(50), "gateway_api_key" text, "gateway_merchant_id" character varying(255), "gateway_webhook_url" character varying(500), "gateway_test_mode" boolean NOT NULL DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_87c6a90ab0fbb3e49e15e829e6" CHECK ((daily_transaction_limit IS NULL OR daily_transaction_limit >= 0)), CONSTRAINT "CHK_b54db5bd872a49ad05c84f7e4a" CHECK ((min_amount IS NULL OR max_amount IS NULL OR max_amount >= min_amount)), CONSTRAINT "CHK_ef661d7b14fdd00edbd6e00c02" CHECK ((max_amount IS NULL OR max_amount >= 0.01)), CONSTRAINT "CHK_718db86e6f008d3b76e1dfdde8" CHECK ((min_amount IS NULL OR min_amount >= 0.01)), CONSTRAINT "CHK_61385182a8626bda14d6c4839b" CHECK ((processing_fee_percent IS NULL OR (processing_fee_percent >= 0 AND processing_fee_percent <= 10))), CONSTRAINT "PK_34f9b8c6dfb4ac3559f7e2820d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_pm_company_gateway_merchant" ON "payment_methods" ("company_id", "gateway_type", "gateway_merchant_id") WHERE gateway_type IS NOT NULL AND gateway_merchant_id IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_pm_company_name" ON "payment_methods" ("company_id", "name") `);
        await queryRunner.query(`CREATE INDEX "idx_pm_company_active" ON "payment_methods" ("company_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_pm_company_type" ON "payment_methods" ("company_id", "type") `);
        await queryRunner.query(`CREATE INDEX "idx_pm_company" ON "payment_methods" ("company_id") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "invoice_id" uuid NOT NULL, "payment_method_id" uuid NOT NULL, "amount" numeric(15,2) NOT NULL, "payment_date" TIMESTAMP WITH TIME ZONE NOT NULL, "transaction_id" character varying(100), "status" character varying(30) NOT NULL, "notes" text, "currency" character varying(3) NOT NULL DEFAULT 'RUB', "exchange_rate" numeric(12,6), "original_amount" numeric(15,2), "original_currency" character varying(3), "gateway_transaction_id" character varying(255), "gateway_fee" numeric(10,2), "gateway_status" character varying(50), "masked_card_number" character varying(20), "card_brand" character varying(50), "vat_rate" numeric(5,2), "vat_amount" numeric(10,2), "fiscal_receipt_number" character varying(50), "fiscal_receipt_date" TIMESTAMP WITH TIME ZONE, "kkt_serial_number" character varying(50), "fiscal_document_number" character varying(50), "fiscal_document_attribute" character varying(50), "fiscal_refund_receipt_number" character varying(50), "fiscal_refund_date" TIMESTAMP WITH TIME ZONE, "pdp_consent_version" character varying(50), "pdp_consent_date" TIMESTAMP WITH TIME ZONE, "data_retention_until" TIMESTAMP WITH TIME ZONE, "pii_anonymized" boolean NOT NULL DEFAULT false, "safe_metadata" jsonb, "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "payment_receipt_date_not_future" CHECK (fiscal_receipt_date IS NULL OR fiscal_receipt_date <= CURRENT_TIMESTAMP), CONSTRAINT "payment_date_not_future" CHECK (payment_date <= CURRENT_TIMESTAMP), CONSTRAINT "payment_vat_amount_non_negative" CHECK (vat_amount IS NULL OR vat_amount >= 0), CONSTRAINT "payment_original_amount_positive" CHECK (original_amount IS NULL OR original_amount > 0), CONSTRAINT "payment_gateway_fee_non_negative" CHECK (gateway_fee IS NULL OR gateway_fee >= 0), CONSTRAINT "payment_exchange_rate_positive" CHECK (exchange_rate IS NULL OR exchange_rate > 0), CONSTRAINT "payment_amount_positive" CHECK (amount > 0), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id")); COMMENT ON COLUMN "payments"."company_id" IS 'ID компании (multi-tenant)'; COMMENT ON COLUMN "payments"."invoice_id" IS 'ID счёта на оплату'; COMMENT ON COLUMN "payments"."payment_method_id" IS 'ID способа оплаты'; COMMENT ON COLUMN "payments"."amount" IS 'Сумма платежа'; COMMENT ON COLUMN "payments"."payment_date" IS 'Дата и время платежа'; COMMENT ON COLUMN "payments"."status" IS 'Статус платежа'; COMMENT ON COLUMN "payments"."notes" IS 'Примечания к платежу (может содержать ПДн)'; COMMENT ON COLUMN "payments"."currency" IS 'Валюта (ISO 4217)'`);
        await queryRunner.query(`CREATE INDEX "IDX_87440a9b7e144768a2fd476a43" ON "payments" ("payment_date", "status") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_a4b1b41e0202ea97a22bcea072" ON "payments" ("company_id", "status", "payment_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_068a82332649f2367d30f7cd66" ON "payments" ("company_id", "currency") `);
        await queryRunner.query(`CREATE INDEX "IDX_a299434060131d6950b76cebf0" ON "payments" ("company_id", "payment_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_b78c91822805cc7c6ab900d817" ON "payments" ("company_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf987cc189a232130a4c3cd7ea" ON "payments" ("fiscal_receipt_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_df19fdcdda2cc58abb42d2a833" ON "payments" ("gateway_transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c324ca49dabde7ffc0ef64675" ON "payments" ("transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb4f745ec0ac3b18b42eff773f" ON "payments" ("currency") `);
        await queryRunner.query(`CREATE INDEX "IDX_685fffacc6464277439d0260ab" ON "payments" ("payment_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_12fd861c33c885f01b9a7da7d9" ON "payments" ("payment_method_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4781cf05f36ba314cdd314c0c6" ON "payments" ("company_id") `);
        await queryRunner.query(`CREATE TABLE "part_reservations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "part_id" uuid NOT NULL, "order_id" uuid, "quantity" integer NOT NULL, "reserved_by" uuid NOT NULL, "reserved_at" TIMESTAMP WITH TIME ZONE NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE, "status" character varying(12) NOT NULL DEFAULT 'active', "released_at" TIMESTAMP WITH TIME ZONE, "released_by" uuid, "idempotency_key" character varying(128), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_34f04a9a9a4624aecb699062e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_reservation_idempotency" ON "part_reservations" ("company_id", "idempotency_key") WHERE idempotency_key IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_94280c1d081a3948d2d28bc992" ON "part_reservations" ("part_id", "company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fb77c88df59423c18a762d436" ON "part_reservations" ("company_id") `);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "partId" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "minQuantity" integer NOT NULL DEFAULT '0', "location" character varying(100), "lastRestockDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "part_id" uuid, CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_alert_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "userId" uuid, "enableEmailNotifications" boolean NOT NULL DEFAULT true, "enablePushNotifications" boolean NOT NULL DEFAULT true, "emailAddresses" text array NOT NULL DEFAULT '{}', "lowStockThreshold" integer NOT NULL DEFAULT '5', "criticalStockThreshold" integer NOT NULL DEFAULT '2', "overstockMultiplier" integer NOT NULL DEFAULT '5', "enabledAlertTypes" text array NOT NULL DEFAULT '{low_stock,out_of_stock,overstock}', "alertFrequency" character varying(20) NOT NULL DEFAULT 'immediate', "autoDismissAfterRestock" boolean NOT NULL DEFAULT true, "autoDismissAfterHours" integer NOT NULL DEFAULT '72', "workingHoursStart" character varying(5), "workingHoursEnd" character varying(5), "workingDays" smallint array, "timezone" character varying(100), "lastNotificationSent" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_alert_settings_company_user" UNIQUE ("companyId", "userId"), CONSTRAINT "chk_alert_settings_auto_hours_range" CHECK ("autoDismissAfterHours" >= 1 AND "autoDismissAfterHours" <= 168), CONSTRAINT "chk_alert_settings_critical_nonneg" CHECK ("criticalStockThreshold" >= 0), CONSTRAINT "chk_alert_settings_low_nonneg" CHECK ("lowStockThreshold" >= 0), CONSTRAINT "PK_fa016443cf4910787bac3e53ffe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_alert_settings_companyid" ON "inventory_alert_settings" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "inventory_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "part_id" uuid NOT NULL, "type" character varying(50) NOT NULL DEFAULT 'low_stock', "priority" character varying(20) NOT NULL DEFAULT 'medium', "title" character varying(200), "message" text, "currentQuantity" integer, "thresholdQuantity" integer, "metadata" jsonb, "isActive" boolean NOT NULL DEFAULT true, "isDismissed" boolean NOT NULL DEFAULT false, "dismissedBy" character varying(255), "dismissedAt" TIMESTAMP WITH TIME ZONE, "triggeredBy" character varying(255), "minQuantity" integer NOT NULL DEFAULT '0', "alertEnabled" boolean NOT NULL DEFAULT true, "alertEmails" text, "notified" boolean NOT NULL DEFAULT false, "lastNotificationDate" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "chk_alert_threshold_qty_nonneg" CHECK ("thresholdQuantity" IS NULL OR "thresholdQuantity" >= 0), CONSTRAINT "chk_alert_current_qty_nonneg" CHECK ("currentQuantity" IS NULL OR "currentQuantity" >= 0), CONSTRAINT "PK_01e1629043f028ec1e59b514e1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_inventory_alerts_createdat" ON "inventory_alerts" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_inventory_alerts_partid" ON "inventory_alerts" ("part_id") `);
        await queryRunner.query(`CREATE INDEX "idx_inventory_alerts_companyid" ON "inventory_alerts" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "company_id" uuid, "action" character varying(150) NOT NULL, "level" character varying(16) NOT NULL DEFAULT 'info', "ip_address" character varying(45), "user_agent" text, "resource_id" character varying(150), "resource_type" character varying(150), "details" jsonb, "status" character varying(32) NOT NULL DEFAULT 'success', "service" character varying(64), "device_id" character varying(150), "chain_prev" character varying(128), "chain_curr" character varying(128) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_audit_chain_curr" ON "audit_logs" ("chain_curr") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_company_created_at" ON "audit_logs" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."appointment_status_enum" AS ENUM('draft', 'scheduled', 'confirmed', 'in_progress', 'completed', 'canceled', 'no_show', 'rescheduled')`);
        await queryRunner.query(`CREATE TYPE "public"."appointment_priority_enum" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "vehicle_id" uuid NOT NULL, "mechanic_id" uuid NOT NULL, "start_time" TIMESTAMP WITH TIME ZONE NOT NULL, "end_time" TIMESTAMP WITH TIME ZONE NOT NULL, "estimated_duration" integer NOT NULL, "actual_duration" integer, "status" "public"."appointment_status_enum" NOT NULL DEFAULT 'draft', "priority" "public"."appointment_priority_enum" NOT NULL DEFAULT 'normal', "service_ids" jsonb NOT NULL DEFAULT '[]'::jsonb, "description" text, "customer_notes" text, "mechanic_notes" text, "contact_phone" character varying(50), "contact_email" character varying(255), "reminder_sent" boolean NOT NULL DEFAULT false, "confirmation_sent" boolean NOT NULL DEFAULT false, "rating" integer, "feedback" text, "estimated_cost" numeric(12,2), "final_cost" numeric(12,2), "data_retention_until" TIMESTAMP WITH TIME ZONE, "anonymized_at" TIMESTAMP WITH TIME ZONE, "anonymized_by" uuid, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "chk_appt_service_ids_array" CHECK (jsonb_typeof(service_ids) = 'array'), CONSTRAINT "chk_appt_costs" CHECK ((estimated_cost IS NULL OR estimated_cost >= 0) AND (final_cost IS NULL OR final_cost >= 0)), CONSTRAINT "chk_appt_rating" CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5)), CONSTRAINT "chk_appt_actual_duration" CHECK (actual_duration IS NULL OR actual_duration >= 0), CONSTRAINT "chk_appt_est_duration" CHECK (estimated_duration >= 0 AND estimated_duration <= 480), CONSTRAINT "chk_appt_time_positive" CHECK (end_time > start_time), CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_appt_company_status_start" ON "appointments" ("company_id", "status", "start_time") `);
        await queryRunner.query(`CREATE INDEX "idx_appt_company_mechanic_start" ON "appointments" ("company_id", "mechanic_id", "start_time") `);
        await queryRunner.query(`CREATE INDEX "idx_appt_company_start" ON "appointments" ("company_id", "start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfbbb460e0ee018217cbea984d" ON "appointments" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_3007a47d97a542e63b3308a69b" ON "appointments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a00d02569b080f2ad57cd133ef" ON "appointments" ("start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_6278563a8ef2f09d0394ba423c" ON "appointments" ("mechanic_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2be3c78815aba227af1c3e8e41" ON "appointments" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0cd63e762f524a499e28903e3" ON "appointments" ("company_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_f0e29920aaf871f3eddbea69f0d" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_models" ADD CONSTRAINT "FK_e71c84a17f9c006260e2d487c01" FOREIGN KEY ("brand_id") REFERENCES "vehicle_brands"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles_service_history" ADD CONSTRAINT "FK_9af62cc972a0a9b7eb56d89b07a" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles_service_history" ADD CONSTRAINT "FK_6c5a6ccfab11cdba2bf2d4b3bc9" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_e11ef2dcd880132d31bd9f92c2a" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_c1cda98f67cb9c79a1f1153e627" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_c4fe98a2147b08df1ab56df5313" FOREIGN KEY ("model_id") REFERENCES "vehicle_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_8c6922f37d6f8a496a4cabfe080" FOREIGN KEY ("vehicle_type_id") REFERENCES "vehicle_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_4bc1204a05dde26383e3955b0a1" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7e3cc01c420db5151aa21360358" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_6d425c9181065f86315cb422ad6" FOREIGN KEY ("tariff_id") REFERENCES "tariffs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_payment_logs" ADD CONSTRAINT "FK_73b063088c84f0070d5c622108c" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_payment_logs" ADD CONSTRAINT "FK_c973220739e2a277deaa8e2ecc8" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_consents" ADD CONSTRAINT "FK_aca8064488e9cb39b7ecd8ea894" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_consents" ADD CONSTRAINT "FK_2b727419f868a56f55677971012" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_consents" ADD CONSTRAINT "FK_b1dbdffb0c0cbfb56f073904ec3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_compliance_logs" ADD CONSTRAINT "FK_073984be2b176a70a12bba6db95" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_compliance_logs" ADD CONSTRAINT "FK_7842d33badf0159a415e5bd29ba" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_compliance_logs" ADD CONSTRAINT "FK_1e5dd851bcdbdb5e57f23573473" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parts" ADD CONSTRAINT "FK_bdf3ba57579988536b6ccfcf988" FOREIGN KEY ("category_id") REFERENCES "part_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_f97a2ef8af9e019a28dba407c98" FOREIGN KEY ("part_id") REFERENCES "parts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_ba50f4ec0ca8df8e44d805c6533" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_services" ADD CONSTRAINT "FK_db8265e367f7c973cd4fe5e17af" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_services" ADD CONSTRAINT "FK_714fa9ff7e2a619c3102352fd18" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_services" ADD CONSTRAINT "FK_7e886c578320ba8364b93266ec2" FOREIGN KEY ("mechanicId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_parts" ADD CONSTRAINT "FK_790f388a94f5ffc752754e3d0f8" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_parts" ADD CONSTRAINT "FK_009833ff74f9f66e1ab72a97320" FOREIGN KEY ("partId") REFERENCES "parts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_b6fe899d5ca4a3f5925463990d1" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_19b96cf049d221b5731e4ed9b7d" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_8d17fd47a7bbf512e58209fbb38" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_8d3f1e17e30b7540ca84036307b" FOREIGN KEY ("assignedTo") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_0b793047e7030ef060eaae8438a" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_a58a78a0e0031dd93a2f56f1e8e" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_4781cf05f36ba314cdd314c0c66" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_12fd861c33c885f01b9a7da7d93" FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part_reservations" ADD CONSTRAINT "FK_60b524abd6aedb7d2c541c1b554" FOREIGN KEY ("part_id") REFERENCES "parts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_0e79b3e3545f78df8b05923d8c8" FOREIGN KEY ("part_id") REFERENCES "parts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_alerts" ADD CONSTRAINT "FK_a92ba282988fc7002ba161f2471" FOREIGN KEY ("part_id") REFERENCES "parts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_d0cd63e762f524a499e28903e3e" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_2be3c78815aba227af1c3e8e413" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_cd5792f585b901b5b379ccb8e67" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_6278563a8ef2f09d0394ba423cc" FOREIGN KEY ("mechanic_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_6278563a8ef2f09d0394ba423cc"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_cd5792f585b901b5b379ccb8e67"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_2be3c78815aba227af1c3e8e413"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_d0cd63e762f524a499e28903e3e"`);
        await queryRunner.query(`ALTER TABLE "inventory_alerts" DROP CONSTRAINT "FK_a92ba282988fc7002ba161f2471"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_0e79b3e3545f78df8b05923d8c8"`);
        await queryRunner.query(`ALTER TABLE "part_reservations" DROP CONSTRAINT "FK_60b524abd6aedb7d2c541c1b554"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_12fd861c33c885f01b9a7da7d93"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_4781cf05f36ba314cdd314c0c66"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_a58a78a0e0031dd93a2f56f1e8e"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_0b793047e7030ef060eaae8438a"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_8d3f1e17e30b7540ca84036307b"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_8d17fd47a7bbf512e58209fbb38"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_19b96cf049d221b5731e4ed9b7d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_b6fe899d5ca4a3f5925463990d1"`);
        await queryRunner.query(`ALTER TABLE "order_parts" DROP CONSTRAINT "FK_009833ff74f9f66e1ab72a97320"`);
        await queryRunner.query(`ALTER TABLE "order_parts" DROP CONSTRAINT "FK_790f388a94f5ffc752754e3d0f8"`);
        await queryRunner.query(`ALTER TABLE "order_services" DROP CONSTRAINT "FK_7e886c578320ba8364b93266ec2"`);
        await queryRunner.query(`ALTER TABLE "order_services" DROP CONSTRAINT "FK_714fa9ff7e2a619c3102352fd18"`);
        await queryRunner.query(`ALTER TABLE "order_services" DROP CONSTRAINT "FK_db8265e367f7c973cd4fe5e17af"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_ba50f4ec0ca8df8e44d805c6533"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_f97a2ef8af9e019a28dba407c98"`);
        await queryRunner.query(`ALTER TABLE "parts" DROP CONSTRAINT "FK_bdf3ba57579988536b6ccfcf988"`);
        await queryRunner.query(`ALTER TABLE "subscription_compliance_logs" DROP CONSTRAINT "FK_1e5dd851bcdbdb5e57f23573473"`);
        await queryRunner.query(`ALTER TABLE "subscription_compliance_logs" DROP CONSTRAINT "FK_7842d33badf0159a415e5bd29ba"`);
        await queryRunner.query(`ALTER TABLE "subscription_compliance_logs" DROP CONSTRAINT "FK_073984be2b176a70a12bba6db95"`);
        await queryRunner.query(`ALTER TABLE "subscription_consents" DROP CONSTRAINT "FK_b1dbdffb0c0cbfb56f073904ec3"`);
        await queryRunner.query(`ALTER TABLE "subscription_consents" DROP CONSTRAINT "FK_2b727419f868a56f55677971012"`);
        await queryRunner.query(`ALTER TABLE "subscription_consents" DROP CONSTRAINT "FK_aca8064488e9cb39b7ecd8ea894"`);
        await queryRunner.query(`ALTER TABLE "subscription_payment_logs" DROP CONSTRAINT "FK_c973220739e2a277deaa8e2ecc8"`);
        await queryRunner.query(`ALTER TABLE "subscription_payment_logs" DROP CONSTRAINT "FK_73b063088c84f0070d5c622108c"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_6d425c9181065f86315cb422ad6"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7e3cc01c420db5151aa21360358"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_4bc1204a05dde26383e3955b0a1"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_8c6922f37d6f8a496a4cabfe080"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_c4fe98a2147b08df1ab56df5313"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_c1cda98f67cb9c79a1f1153e627"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_e11ef2dcd880132d31bd9f92c2a"`);
        await queryRunner.query(`ALTER TABLE "vehicles_service_history" DROP CONSTRAINT "FK_6c5a6ccfab11cdba2bf2d4b3bc9"`);
        await queryRunner.query(`ALTER TABLE "vehicles_service_history" DROP CONSTRAINT "FK_9af62cc972a0a9b7eb56d89b07a"`);
        await queryRunner.query(`ALTER TABLE "vehicle_models" DROP CONSTRAINT "FK_e71c84a17f9c006260e2d487c01"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_f0e29920aaf871f3eddbea69f0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0cd63e762f524a499e28903e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2be3c78815aba227af1c3e8e41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6278563a8ef2f09d0394ba423c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a00d02569b080f2ad57cd133ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3007a47d97a542e63b3308a69b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfbbb460e0ee018217cbea984d"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appt_company_start"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appt_company_mechanic_start"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appt_company_status_start"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`DROP TYPE "public"."appointment_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."appointment_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_company_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."uq_audit_chain_curr"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inventory_alerts_companyid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inventory_alerts_partid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inventory_alerts_createdat"`);
        await queryRunner.query(`DROP TABLE "inventory_alerts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_alert_settings_companyid"`);
        await queryRunner.query(`DROP TABLE "inventory_alert_settings"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4fb77c88df59423c18a762d436"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94280c1d081a3948d2d28bc992"`);
        await queryRunner.query(`DROP INDEX "public"."uq_reservation_idempotency"`);
        await queryRunner.query(`DROP TABLE "part_reservations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4781cf05f36ba314cdd314c0c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12fd861c33c885f01b9a7da7d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_685fffacc6464277439d0260ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb4f745ec0ac3b18b42eff773f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c324ca49dabde7ffc0ef64675"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df19fdcdda2cc58abb42d2a833"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf987cc189a232130a4c3cd7ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b78c91822805cc7c6ab900d817"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a299434060131d6950b76cebf0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_068a82332649f2367d30f7cd66"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4b1b41e0202ea97a22bcea072"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87440a9b7e144768a2fd476a43"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pm_company"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pm_company_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pm_company_active"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_pm_company_name"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_pm_company_gateway_merchant"`);
        await queryRunner.query(`DROP TABLE "payment_methods"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b793047e7030ef060eaae8438"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a58a78a0e0031dd93a2f56f1e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41ee6a6636d48aac700fb52e0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_affa881df04ba2db0fce590be4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5306b1cb7e79346085c73c0480"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6fe899d5ca4a3f5925463990d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5de51ca888d8b1f5ac25799dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19b96cf049d221b5731e4ed9b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d17fd47a7bbf512e58209fbb3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d3f1e17e30b7540ca84036307"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60cc1394b230eb43e4e415eda3"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_790f388a94f5ffc752754e3d0f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_009833ff74f9f66e1ab72a9732"`);
        await queryRunner.query(`DROP TABLE "order_parts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db8265e367f7c973cd4fe5e17a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_714fa9ff7e2a619c3102352fd1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e886c578320ba8364b93266ec"`);
        await queryRunner.query(`DROP TABLE "order_services"`);
        await queryRunner.query(`DROP TABLE "service_categories"`);
        await queryRunner.query(`DROP INDEX "public"."idx_se_company_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_se_company_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_se_company_start_end"`);
        await queryRunner.query(`DROP INDEX "public"."idx_se_company_retention"`);
        await queryRunner.query(`DROP TABLE "schedule_exceptions"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_exceptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_exceptions_type_enum"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_parts_companyid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_parts_categoryid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_parts_createdat"`);
        await queryRunner.query(`DROP INDEX "public"."idx_parts_company_partnumber_unique"`);
        await queryRunner.query(`DROP TABLE "parts"`);
        await queryRunner.query(`DROP TABLE "part_categories"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comp_logs_company_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81fbd794573a01d5e004f85c84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a3c76ee765376431d8f927858"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c74a5323cfdb34d2acc50aff6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67b1f10f57ded0fb49d46477e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7842d33badf0159a415e5bd29b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_073984be2b176a70a12bba6db9"`);
        await queryRunner.query(`DROP TABLE "subscription_compliance_logs"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_compliance_risk_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_compliance_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_compliance_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_compliance_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_active_consent_per_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_860ee1954cafb7cde803ee9444"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e308eb9e8f2abc30eaa067959b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0b580252fad2055064fdca4a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b727419f868a56f5567797101"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aca8064488e9cb39b7ecd8ea89"`);
        await queryRunner.query(`DROP TABLE "subscription_consents"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_consent_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_consent_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_gateway_tx"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29b75ed40678523f6f34c8e584"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e44cc8ba7fa6c080a4810bba08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46b3c58aadafa36dc09dc56dac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05ed0c14282337b6b6da805c01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_569039d8fb7f0d507e8296d9b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c40c4d9508a8edfad0104b8e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c973220739e2a277deaa8e2ecc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73b063088c84f0070d5c622108"`);
        await queryRunner.query(`DROP TABLE "subscription_payment_logs"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_payment_method_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_payment_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscriptions_company_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscriptions_company_end_date"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_active_subscription_per_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_349405bc66ac45d86a24f562e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e3cc01c420db5151aa2136035"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_suppliers_companyid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_suppliers_isactive"`);
        await queryRunner.query(`DROP INDEX "public"."idx_suppliers_company_email_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_suppliers_company_taxnumber_unique"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_suppliertype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tariffs_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tariffs_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tariffs_name"`);
        await queryRunner.query(`DROP TABLE "tariffs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc51c44e296132242ed415f181"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6283f1222bdc2390cf16836ce7"`);
        await queryRunner.query(`DROP TABLE "user_consents"`);
        await queryRunner.query(`DROP TABLE "user_sessions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e11ef2dcd880132d31bd9f92c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1cda98f67cb9c79a1f1153e62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33467e9fe9f0278ffc281ccba9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_534329c0c56af9bd284a18acc6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_805f65c04948d4e5006b3b2de2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_216b6063df0b6aedf55180f91f"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9af62cc972a0a9b7eb56d89b07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c5a6ccfab11cdba2bf2d4b3bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a99214791d317ed73db1c4969"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3866b386f2136abf529d03d122"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e96c683d729bb813d19ae173cb"`);
        await queryRunner.query(`DROP TABLE "vehicles_service_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_007a712afe075e18d9d822f6fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74a36c6f923c86278b726e9881"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8caa82b996288ac4e7a3090ff4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0474220020aff2d7f6d3b80a27"`);
        await queryRunner.query(`DROP TABLE "vehicle_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e71c84a17f9c006260e2d487c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bddf5fcb0c09ab5d6ccd46e8d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eea946a495b5724fd8b31149aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d03b990e547e1715fd8083399a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92932f12363389355657c9f54a"`);
        await queryRunner.query(`DROP TABLE "vehicle_models"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11f4754bf8fc4c02fd6d964724"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47141a92885dcbcab5cc815f1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7a9a7fe16791a075d6c4f9bf5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a934f45da52f7519d515cd1df0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f5a532698b4aabfd1526c4745"`);
        await queryRunner.query(`DROP TABLE "vehicle_brands"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0e29920aaf871f3eddbea69f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_946a7a5519eab49537ba6be271"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_580988896ad56541ddab92aace"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49fcf0b823276d66af6f0c3868"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a21e0c622ad0d6376e813e4317"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f4e9c088ad9e60af1a7d1193d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d0632c00306eec5feecbbdc9f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b559ae26b6f801536d28109453"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_774de87b5d9acde9112a1645ef"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP INDEX "public"."idx_work_schedule_company"`);
        await queryRunner.query(`DROP INDEX "public"."idx_work_schedule_company_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_work_schedule_company_day"`);
        await queryRunner.query(`DROP TABLE "work_schedules"`);
    }

}
